DROP TABLE IF EXISTS syslog.rh_ausencia;
DROP TABLE IF EXISTS syslog.rh_ausencia_tipo;
DROP TABLE IF EXISTS syslog.rh_ausencia_clase;
DROP TABLE IF EXISTS syslog.rh_vacancia;
DROP TABLE IF EXISTS syslog.rh_plaza;
DROP TABLE IF EXISTS syslog.rh_puesto;
DROP TABLE IF EXISTS syslog.rh_trab;
DROP TABLE IF EXISTS syslog.rh_descanso;
DROP TABLE IF EXISTS syslog.rh_jornada;
