CREATE TABLE IF NOT EXISTS syslog.t01_puesto (
    clave INTEGER UNSIGNED  NOT NULL,
    descr VARCHAR(55) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
    nombre VARCHAR(55),
    puesto_stps VARCHAR(55),
    clave_stps INT,
    activo TINYINT NOT NULL DEFAULT 1,
    id_rev INTEGER UNSIGNED NOT NULL,
    id_reg_cont INTEGER UNSIGNED NOT NULL,
    nivel TINYINT UNSIGNED NOT NULL,
    familia TINYINT UNSIGNED NOT NULL,
    labores TINYINT UNSIGNED NOT NULL,
    regimen VARCHAR(1) NOT NULL,
    clasif VARCHAR(8) NOT NULL,
    PRIMARY KEY(clave)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;
