INSERT INTO syslog.t01_ausencia_tipo (id, nombre, descr, clave_ausencia) VALUES (2, 'VAE', 'VACACIONES EXTEMPORANEAS', 'VA');
INSERT INTO syslog.t01_ausencia_tipo (id, nombre, descr, clave_ausencia) VALUES (3, 'CL150', 'PERMISO ECONOMICO', 'PE');
INSERT INTO syslog.t01_ausencia_tipo (id, nombre, descr, clave_ausencia) VALUES (4, 'CL147', 'PEREMISO RENUNCIABLE', 'PE');
INSERT INTO syslog.t01_ausencia_tipo (id, nombre, descr, clave_ausencia) VALUES (5, 'CL148', 'PERMISO 90 DIAS', 'PE');
INSERT INTO syslog.t01_ausencia_tipo (id, nombre, descr, clave_ausencia) VALUES (6, 'CL149', 'PERMISO 6 AÑOS', 'PE');
INSERT INTO syslog.t01_ausencia_tipo (id, nombre, descr, clave_ausencia) VALUES (7, 'CL103', 'EXAMENES MEDICO', 'ME');
INSERT INTO syslog.t01_ausencia_tipo (id, nombre, descr, clave_ausencia) VALUES (8, 'CL104', 'ATENCION MEDICA', 'ME');
INSERT INTO syslog.t01_ausencia_tipo (id, nombre, descr, clave_ausencia) VALUES (9, 'COA', 'COMISION ADMINISTRATIVA', 'CO');
INSERT INTO syslog.t01_ausencia_tipo (id, nombre, descr, clave_ausencia) VALUES (10, 'COS', 'COMISION SINDICAL', 'CO');
INSERT INTO syslog.t01_ausencia_tipo (id, nombre, descr, clave_ausencia) VALUES (11, 'ASD', 'ASCENSO DEFINITIVO', 'AS');
INSERT INTO syslog.t01_ausencia_tipo (id, nombre, descr, clave_ausencia) VALUES (12, 'AST', 'ASCENSO TEMPORAL', 'AS');
INSERT INTO syslog.t01_ausencia_tipo (id, nombre, descr, clave_ausencia) VALUES (13, 'JUB', 'JUBILACION', 'TE');
INSERT INTO syslog.t01_ausencia_tipo (id, nombre, descr, clave_ausencia) VALUES (14, 'LIQ', 'LIQUIDACION', 'TE');
INSERT INTO syslog.t01_ausencia_tipo (id, nombre, descr, clave_ausencia) VALUES (15, 'REC', 'DESPIDO', 'TE');
INSERT INTO syslog.t01_ausencia_tipo (id, nombre, descr, clave_ausencia) VALUES (16, 'NEG', 'PERMISO NEGOCIADO', 'PE');
INSERT INTO syslog.t01_ausencia_tipo (id, nombre, descr, clave_ausencia) VALUES (17, 'CL119', 'ATENCION MEDICA FORANEA', 'ME');
INSERT INTO syslog.t01_ausencia_tipo (id, nombre, descr, clave_ausencia) VALUES (18, 'CAC', 'CAPACITACION CONTRACTUAL', 'CA');
INSERT INTO syslog.t01_ausencia_tipo (id, nombre, descr, clave_ausencia) VALUES (19, 'CAP', 'CAPACITACION PROFESIONAL', 'CA');
INSERT INTO syslog.t01_ausencia_tipo (id, nombre, descr, clave_ausencia) VALUES (20, 'FI', 'FALTA INJUSTIFICADA', 'FA');
INSERT INTO syslog.t01_ausencia_tipo (id, nombre, descr, clave_ausencia) VALUES (21, 'DE', 'AUSENCIA DESCONOCIDA', 'FA');
INSERT INTO syslog.t01_ausencia_tipo (id, nombre, descr, clave_ausencia) VALUES (22, 'SAA', 'SANCION ADMINISTRATIVA', 'SA');
INSERT INTO syslog.t01_ausencia_tipo (id, nombre, descr, clave_ausencia) VALUES (23, 'SAS', 'SANCION SINDICAL', 'SA');
INSERT INTO syslog.t01_ausencia_tipo (id, nombre, descr, clave_ausencia) VALUES (24, 'VAJ', 'VACACIONES PRE-JUBILATORIAS', 'VA');
INSERT INTO syslog.t01_ausencia_tipo (id, nombre, descr, clave_ausencia) VALUES (25, 'DDP', 'DISPOSICION DE PERSONAL', 'FA');
INSERT INTO syslog.t01_ausencia_tipo (id, nombre, descr, clave_ausencia) VALUES (26, 'NUE', 'PLAZA NUEVA', 'CR');
INSERT INTO syslog.t01_ausencia_tipo (id, nombre, descr, clave_ausencia) VALUES (27, 'VEN', 'VENCIMIENTO DE PLAZA OD', 'RE');

