INSERT INTO t01_vacancia (id, nombre, descr) VALUES ('1', 'AUSENCIA', 'VACANCIA GENERADA POR ALGUN TIPO DE AUSENCIA DEL ASIGNADO A LA PLAZA EN CUESTION');
INSERT INTO t01_vacancia (id, nombre, descr) VALUES ('2', 'TERMINACION', 'GENERADA POR TERMINACION DEFINITIVA DEL TRABAJADOR QUE TIENE ASIGNADA LA PLAZA EN FORMA DEFINITIVA (JUBILACION, LIQUIDACION, RECISION DE CONTRATO)');
INSERT INTO t01_vacancia (id, nombre, descr) VALUES ('3', 'CREACION', 'VACANCIA GENERADA POR LA CREACIÓN DE LA PLAZA (PLAZA NUEVA)');
INSERT INTO t01_vacancia (id, nombre, descr) VALUES ('4', 'RENOVACION', 'VACANCIA GENERADA POR LA TERMINACION TEMPORAL DE LA VIGENCIA DE LA PLAZA (RENOVACION DE PLAZA). PARA UNA TERMINACION DEFINITIVA SE TIENE QUE DESHABILITAR LA PLAZA EN CUESTION.');

