CREATE TABLE IF NOT EXISTS id6533743_syslog.rh_vacancia (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT, 
	nombre VARCHAR(15) NOT NULL, 
	descr VARCHAR(50) NOT NULL, 
	PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

INSERT INTO id6533743_syslog.rh_vacancia (nombre, descr) VALUES ('AUSENCIA', 'AUSENCIA GENERADA POR ALGUN TIPO DE AUSENCIA DEL ASIGNADO A LA PLAZA EN CUESTION');
INSERT INTO id6533743_syslog.rh_vacancia (nombre, descr) VALUES ('TERMINACION', 'GENERADA POR TERMINACION DEFINITIVA DEL TRABAJADOR QUE TIENE ASIGNADA LA PLAZA EN FORMA DEFINITIVA (JUBILACION, LIQUIDACION, RECISION DE CONTRATO)');
INSERT INTO id6533743_syslog.rh_vacancia (nombre, descr) VALUES ('CREACION', 'GENERADA POR LA CREACIÓN DE LA PLAZA (PLAZA NUEVA)');
INSERT INTO id6533743_syslog.rh_vacancia (nombre, descr) VALUES ('RENOVACION', 'GENERADA POR LA TERMINACION TEMPORAL DE LA VIGENCIA DE LA PLAZA (RENOVACION DE PLAZA). PARA UNA TERMINACION DEFINITIVA SE TIENE QUE DESHABILITAR LA PLAZA EN CUESTION.');
