CREATE TABLE IF NOT EXISTS syslog.t01_trab (
    clave INTEGER UNSIGNED NOT NULL,
    nombre VARCHAR(40) NOT NULL,
    ap_pat VARCHAR(40) NOT NULL,
    ap_mat VARCHAR(40),
    ncorto VARCHAR(80),
    apodo VARCHAR(35),
    activo TINYINT NOT NULL DEFAULT 1,
    curp VARCHAR(18),
    rfc VARCHAR(15),
    calle_no VARCHAR(35),
    colonia VARCHAR(35),
    ciudad VARCHAR(25),
    estado VARCHAR(25),
    pais VARCHAR(25) DEFAULT 'MEXICO',
    nacionalidad VARCHAR(25) DEFAULT 'MEXICANA',
    edo_civil ENUM('SOLTERO', 'CASADO', 'VIUDO', 'SEPARADO', 'UNION LIBRE'),
    sexo ENUM('MASCULINO', 'FEMENINO'),
    tel VARCHAR(25),
    email VARCHAR(80),
    fec_cat DATE,
    fec_depto DATE,
    fec_planta DATE,
    fec_ingreso DATE,
    fec_nac DATE,
    reg_cont ENUM('P', 'T'),
    reg_sind ENUM('S', 'C'),
    PRIMARY KEY(clave),
    INDEX IDX_nombre(nombre ASC),
    INDEX IDX_ape(ap_pat ASC)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;
